on:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on:  windows-latest

    steps:
      - use: actions/checkout@v2
      - use: actions/setup-node@v1
      - use: microsoft/playwright-github-action@v1

      - name: Install dependecies
        run: npm install

      - name: run test
        run: npm test


